-- Обновление картинок упражнений (source: yuhonas/free-exercise-db)
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg' WHERE name = 'Жим штанги лёжа';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg' WHERE name = 'Жим гантелей лёжа';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg' WHERE name = 'Жим штанги на наклонной скамье';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg' WHERE name = 'Жим гантелей на наклонной скамье';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg' WHERE name = 'Разводка гантелей лёжа';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Up_Wide/0.jpg' WHERE name = 'Отжимания';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Chest_Version/0.jpg' WHERE name = 'Отжимания на брусьях';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg' WHERE name = 'Кроссовер на блоках';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg' WHERE name = 'Пуловер с гантелью';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg' WHERE name = 'Подтягивания';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg' WHERE name = 'Тяга штанги в наклоне';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg' WHERE name = 'Тяга гантели в наклоне';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg' WHERE name = 'Тяга верхнего блока к груди';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg' WHERE name = 'Тяга нижнего блока сидя';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg' WHERE name = 'Становая тяга';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/0.jpg' WHERE name = 'Гиперэкстензия';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg' WHERE name = 'Шраги со штангой';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shrug/0.jpg' WHERE name = 'Шраги с гантелями';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg' WHERE name = 'Приседания со штангой';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Squat/0.jpg' WHERE name = 'Приседания с гантелями';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg' WHERE name = 'Жим ногами';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg' WHERE name = 'Выпады с гантелями';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg' WHERE name = 'Румынская тяга';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg' WHERE name = 'Сгибание ног в тренажёре';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg' WHERE name = 'Разгибание ног в тренажёре';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg' WHERE name = 'Ягодичный мостик';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg' WHERE name = 'Ягодичный мостик со штангой';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg' WHERE name = 'Подъём на носки стоя';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg' WHERE name = 'Подъём на носки сидя';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg' WHERE name = 'Приседания Сумо';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Split_Squat_with_Dumbbells/0.jpg' WHERE name = 'Болгарские выпады';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shoulder_Press/0.jpg' WHERE name = 'Жим штанги стоя';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg' WHERE name = 'Жим гантелей сидя';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg' WHERE name = 'Разводка гантелей стоя';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg' WHERE name = 'Подъём гантелей в стороны сидя';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg' WHERE name = 'Тяга штанги к подбородку';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg' WHERE name = 'Тяга гантели к подбородку';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg' WHERE name = 'Подъём гантелей перед собой';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg' WHERE name = 'Жим Арнольда';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rear_Delt_Fly/0.jpg' WHERE name = 'Обратная разводка в тренажёре';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_with_Head_on_Bench/0.jpg' WHERE name = 'Разводка гантелей в наклоне';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg' WHERE name = 'Подъём штанги на бицепс';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg' WHERE name = 'Подъём гантелей на бицепс';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg' WHERE name = 'Молотки';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg' WHERE name = 'Подъём на бицепс на скамье Скотта';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg' WHERE name = 'Концентрированный подъём';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/0.jpg' WHERE name = 'Подъём на бицепс на блоке';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg' WHERE name = 'Подъём гантелей на бицепс на наклонной скамье';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/0.jpg' WHERE name = 'Отжимания на брусьях (трицепс)';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/0.jpg' WHERE name = 'Французский жим лёжа';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg' WHERE name = 'Разгибание на блоке';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg' WHERE name = 'Жим узким хватом';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_One-Arm_Triceps_Extension/0.jpg' WHERE name = 'Разгибание гантели из-за головы';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Tricep_Kickback/0.jpg' WHERE name = 'Разгибание гантели в наклоне (кикбэк)';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/French_Press_-_Decline/0.jpg' WHERE name = 'Французский жим с гантелями';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg' WHERE name = 'Разгибание на блоке обратным хватом';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg' WHERE name = 'Отжимания от скамьи';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg' WHERE name = 'Обратные отжимания от скамьи';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg' WHERE name = 'Скручивания';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg' WHERE name = 'Планка';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Leg_Pull-In/0.jpg' WHERE name = 'Подъём ног лёжа';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Air_Bike/0.jpg' WHERE name = 'Велосипед';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg' WHERE name = 'Подъём ног в висе';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Knee_Tuck_Jump/0.jpg' WHERE name = 'Подъём коленей в висе';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg' WHERE name = 'Русский твист';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Plank/0.jpg' WHERE name = 'Планка на боку';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/0.jpg' WHERE name = 'Ролик для пресса';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Crunch/0.jpg' WHERE name = 'Скручивания на наклонной скамье';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Crunch/0.jpg' WHERE name = 'Обратные скручивания';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/0.jpg' WHERE name = 'Альпинист';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Burpee/0.jpg' WHERE name = 'Берпи';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jumping_Jacks/0.jpg' WHERE name = 'Джампинг-джеки';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Knee_Squat/0.jpg' WHERE name = 'Высокие колени';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg' WHERE name = 'Становая тяга Сумо';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg' WHERE name = 'Зашагивания на платформу';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg' WHERE name = 'Зашагивания на платформу с гантелями';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunge/0.jpg' WHERE name = 'Выпады назад';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunge/0.jpg' WHERE name = 'Выпады назад с гантелями';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Lunge/0.jpg' WHERE name = 'Выпады со штангой';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg' WHERE name = 'Приседания без оборудования';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sissy_Squat/0.jpg' WHERE name = 'Гакк-приседания';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Leg_Barbell_Squat/0.jpg' WHERE name = 'Приседания на одной ноге (пистолет)';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Swing/0.jpg' WHERE name = 'Махи гирей';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Swings/0.jpg' WHERE name = 'Рывок гири';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Jump_Squat/0.jpg' WHERE name = 'Прыжки на тумбу';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Up_with_Clap/0.jpg' WHERE name = 'Отжимания с хлопком';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Treadmill/0.jpg' WHERE name = 'Бег на беговой дорожке';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jump_Rope/0.jpg' WHERE name = 'Прыжки со скакалкой';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stationary_Bike_Run/0.jpg' WHERE name = 'Велотренажёр';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Ergometer/0.jpg' WHERE name = 'Гребной тренажёр';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg' WHERE name = 'Тяга горизонтального блока';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg' WHERE name = 'Подтягивания обратным хватом';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg' WHERE name = 'Тяга верхнего блока узким хватом';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg' WHERE name = 'Тяга к лицу на блоке';
UPDATE exercises SET animation_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg' WHERE name = 'Тяга гантелей к поясу лёжа';
